# Generated by Django 4.2.6 on 2023-11-14 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_alter_application_animal'),
        ('accounts', '0004_alter_myuser_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnShelter',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_shelter', to='accounts.petshelter')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentonshelter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentOnApplication',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentonapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
