# Generated by Django 5.0 on 2023-12-05 23:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnApplication',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commenter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentOnBlogPost',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commenter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentOnShelter',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commenter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_shelter', to='accounts.petshelter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
