# Generated by Django 4.2.6 on 2023-11-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_myuser_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('self_desc', models.TextField()),
                ('exp_pets', models.TextField()),
                ('diff_owners', models.TextField()),
                ('food_check', models.BooleanField()),
                ('water_check', models.BooleanField()),
                ('shelter_check', models.BooleanField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.pet')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.petseeker')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.petshelter')),
            ],
        ),
    ]
