# Generated by Django 4.2 on 2023-11-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petlistings.pet'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
