# Generated by Django 4.2 on 2023-11-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0001_initial'),
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'animal')},
        ),
    ]
