# Generated by Django 4.2.6 on 2023-11-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0001_initial'),
        ('applications', '0002_alter_application_animal_delete_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='animal',
            field=models.ForeignKey(limit_choices_to={'status': 'available'}, on_delete=django.db.models.deletion.CASCADE, to='petlistings.pet'),
        ),
    ]
