# Generated by Django 4.2 on 2023-11-13 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_myuser_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('adopted', 'Adopted')], max_length=10)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.petshelter')),
            ],
        ),
    ]
