# Generated by Django 4.2.6 on 2023-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('withdrawn', 'Withdrawn'), ('adopted', 'Adopted')], max_length=10),
        ),
    ]
