# Generated by Django 4.2.6 on 2023-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0003_alter_pet_name_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('adopted', 'Adopted')], max_length=10),
        ),
    ]
