# Generated by Django 4.2.7 on 2023-11-11 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petseeker",
            name="user",
        ),
        migrations.RemoveField(
            model_name="petshelter",
            name="user",
        ),
    ]
