# Generated by Django 4.2.7 on 2023-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_myuser_is_seeker_myuser_is_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="user_avatar",
            field=models.ImageField(blank=True, upload_to="account/avatar/"),
        ),
        migrations.AlterField(
            model_name="petshelter",
            name="shelter_avatar",
            field=models.ImageField(blank=True, upload_to="shelter/avatar/"),
        ),
    ]
