# Generated by Django 5.0 on 2023-12-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.petshelter')),
            ],
        ),
    ]
