# Generated by Django 4.2.6 on 2023-11-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_animal'),
        ('comments', '0003_commentonapplication_commenter_name_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_on_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentonapplication'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_on_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentonshelter'),
        ),
    ]
